<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>NPV and IRR calculator</Title>
    <Authors>JPS</Authors>
    <Description>Project management NET Present Value (NPV) and Internal Rate of Return (IRR) calculator.</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn> <!-- Suppress missing XML comment warnings -->
    <Version>1.0.0-alpha.0</Version>   
    <RepositoryUrl>https://github.com/zerihal/NPVCalculator</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/zerihal/NPVCalculator</PackageProjectUrl>
  </PropertyGroup>

</Project>
